/**
 * Generated-sites page — lists clients that were created by the
 * programmatic SEO `client_per_row` flow (i.e. they have one or more
 * rows in `generated_pages`).
 *
 * Separates the auto-generated long tail from the manually-managed
 * Proxied Sites list. At agency scale a single template-run can mint
 * 100+ clients; mixing them with hand-curated clients makes the main
 * list unusable.
 *
 * Bulk delete uses the same soft-delete semantics as the per-client
 * flow (status=paused + deleted_at=NOW, reversible until the 30-day
 * cron sweep). Confirmation is type-`DELETE` once for the whole
 * batch instead of typing N client_ids — operators rarely want to
 * type 100 ids one by one.
 */

import {
  type AppEnv,
  type ClientRow,
  type FlashMessage,
  actorOf,
  canSeeAllClients,
  checkCsrf,
  esc,
  flashRedirect,
  fnvHash,
  invalidateKv,
  loadVisibleClient,
  writeAudit,
} from "./app.js";
import type { User } from "./auth.js";

export interface GeneratedSiteRow extends ClientRow {
  /** Template that produced this site. */
  template_id: number;
  template_name: string;
  /** Data source the template was rendered against. */
  data_source_id: number;
  data_source_name: string;
  /** Number of `generated_pages` rows for this client × template. */
  page_count: number;
  /** Most recent generated_pages.created_at. */
  last_generated_at: string;
}

/**
 * Load every client that has at least one `generated_pages` row, with
 * template + data_source joined in for display. One row per (client,
 * template, data_source) — if the same client was generated by
 * multiple templates it appears multiple times (rare in practice).
 */
export async function loadGeneratedSites(env: AppEnv, user: User): Promise<GeneratedSiteRow[]> {
  const sql = canSeeAllClients(user)
    ? `SELECT c.*,
              g.template_id, t.name AS template_name,
              g.data_source_id, d.name AS data_source_name,
              COUNT(g.id) AS page_count,
              MAX(g.created_at) AS last_generated_at
       FROM clients c
       INNER JOIN generated_pages g ON g.client_id = c.client_id
       LEFT JOIN site_templates t ON t.id = g.template_id
       LEFT JOIN site_data_sources d ON d.id = g.data_source_id
       GROUP BY c.client_id, g.template_id, g.data_source_id
       ORDER BY MAX(g.created_at) DESC, c.client_id`
    : `SELECT c.*,
              g.template_id, t.name AS template_name,
              g.data_source_id, d.name AS data_source_name,
              COUNT(g.id) AS page_count,
              MAX(g.created_at) AS last_generated_at
       FROM clients c
       INNER JOIN generated_pages g ON g.client_id = c.client_id
       LEFT JOIN site_templates t ON t.id = g.template_id
       LEFT JOIN site_data_sources d ON d.id = g.data_source_id
       WHERE c.owner_id = ?
       GROUP BY c.client_id, g.template_id, g.data_source_id
       ORDER BY MAX(g.created_at) DESC, c.client_id`;
  const stmt = env.CONFIG_DB.prepare(sql);
  const r = canSeeAllClients(user)
    ? await stmt.all<GeneratedSiteRow>()
    : await stmt.bind(user.id).all<GeneratedSiteRow>();
  return r.results ?? [];
}

/**
 * Return the set of client_ids that have ≥1 row in `generated_pages`.
 * Used by `/app/clients` to filter them out by default so the main
 * list isn't drowned in auto-generated long tail.
 */
export async function loadGeneratedClientIds(env: AppEnv): Promise<Set<string>> {
  const r = await env.CONFIG_DB.prepare("SELECT DISTINCT client_id FROM generated_pages").all<{
    client_id: string;
  }>();
  return new Set((r.results ?? []).map((x) => x.client_id));
}

/* ─── List page ─── */

const GENERATED_CSS = `
.gen-page .filters{display:flex;gap:.5rem;flex-wrap:wrap;align-items:center;margin:.5rem 0 .75rem}
.gen-page .bulk-bar{background:var(--bg-elevated);border:1px solid var(--border);border-radius:var(--radius);padding:.6rem .9rem;margin:.5rem 0;display:flex;align-items:center;gap:.75rem;font-size:.85rem}
.gen-page .bulk-bar.has-selection{border-color:var(--accent);background:var(--accent-soft)}
.gen-page .bulk-bar .selection-count{font-weight:600;color:var(--accent)}
.gen-page .bulk-bar button{font-size:.82rem;padding:.3rem .65rem}
.gen-page table.data input[type="checkbox"]{cursor:pointer}
.gen-page table.data tr.is-deleted{opacity:.55}
.gen-page .deleted-badge{display:inline-block;font-size:.7rem;padding:.05rem .4rem;background:var(--amber-bg);color:var(--amber);border-radius:9999px;margin-left:.4rem}
`;

export function renderGeneratedSitesList(opts: {
  rows: readonly GeneratedSiteRow[];
  user: User;
  showDeleted: boolean;
}): string {
  const { rows, user, showDeleted } = opts;
  const deletedToggle = showDeleted
    ? `<a href="/app/generated-sites" class="btn" style="font-size:.82rem;padding:.3rem .65rem">Hide deleted</a>`
    : `<a href="/app/generated-sites?show_deleted=1" class="btn" style="font-size:.82rem;padding:.3rem .65rem;color:var(--fg-muted)">Show deleted</a>`;
  const subtitle =
    user.role === "super_admin"
      ? "All programmatic-SEO sites across the platform (super-admin)."
      : `${rows.length} site${rows.length === 1 ? "" : "s"} produced by your templates.`;

  if (rows.length === 0) {
    return `<style>${GENERATED_CSS}</style><div class="gen-page">
      <h1>Generated sites</h1>
      <p class="subtitle">${esc(subtitle)} ${deletedToggle}</p>
      <div class="empty">Nothing yet. Pick a template + data source on <a href="/app/templates">/app/templates</a> and run Generate.</div>
    </div>`;
  }

  const tbody = rows
    .map((r) => {
      const deletedAttr = r.deleted_at ? ' class="is-deleted"' : "";
      const deletedBadge = r.deleted_at ? `<span class="deleted-badge">deleted</span>` : "";
      return `<tr${deletedAttr}>
        <td><input type="checkbox" name="client_id" value="${esc(r.client_id)}" class="bulk-check"></td>
        <td><a href="/app/clients/${esc(r.client_id)}" class="mono">${esc(r.client_id)}</a>${deletedBadge}</td>
        <td><a href="https://${esc(r.proxy_domain)}/" class="mono" target="_blank" rel="noopener">${esc(r.proxy_domain)}</a></td>
        <td><a href="/app/templates/${r.template_id}/edit" style="font-size:.85rem">${esc(r.template_name ?? "(deleted template)")}</a></td>
        <td><a href="/app/data-sources/${r.data_source_id}/edit" style="font-size:.85rem">${esc(r.data_source_name ?? "(deleted data source)")}</a></td>
        <td class="num" style="text-align:right;font-variant-numeric:tabular-nums">${r.page_count}</td>
        <td class="mono" style="font-size:.78rem;color:var(--fg-muted)">${esc(r.last_generated_at)}</td>
      </tr>`;
    })
    .join("");

  return `<style>${GENERATED_CSS}</style><div class="gen-page">
    <h1>Generated sites</h1>
    <p class="subtitle">${esc(subtitle)} ${deletedToggle}</p>
    <form method="GET" action="/app/generated-sites/bulk-delete" id="bulk-form">
      <div class="bulk-bar" id="bulk-bar">
        <label style="display:inline-flex;align-items:center;gap:.4rem;cursor:pointer">
          <input type="checkbox" id="bulk-toggle"> Select all on page
        </label>
        <span style="color:var(--fg-muted)">·</span>
        <span><span class="selection-count" id="selection-count">0</span> selected</span>
        <span style="flex:1"></span>
        <button class="btn" type="submit" id="bulk-delete-btn" disabled style="background:var(--red-bg);color:var(--red);border-color:color-mix(in srgb,var(--red) 30%,transparent)">Bulk delete selected →</button>
      </div>
      <table class="data">
        <thead><tr>
          <th style="width:2.5rem"></th>
          <th>Client</th>
          <th>Proxy domain</th>
          <th>Template</th>
          <th>Data source</th>
          <th class="num">Pages</th>
          <th>Last generated</th>
        </tr></thead>
        <tbody>${tbody}</tbody>
      </table>
    </form>
    <script>
      (function(){
        var form = document.getElementById('bulk-form');
        var toggle = document.getElementById('bulk-toggle');
        var checks = form.querySelectorAll('.bulk-check');
        var btn = document.getElementById('bulk-delete-btn');
        var bar = document.getElementById('bulk-bar');
        var count = document.getElementById('selection-count');
        function recount(){
          var n = 0;
          checks.forEach(function(c){ if(c.checked) n++; });
          count.textContent = n;
          btn.disabled = n === 0;
          if (n > 0) { bar.classList.add('has-selection'); btn.textContent = 'Bulk delete ' + n + ' site' + (n===1?'':'s') + ' →'; }
          else { bar.classList.remove('has-selection'); btn.textContent = 'Bulk delete selected →'; }
        }
        toggle.addEventListener('change', function(){
          checks.forEach(function(c){ c.checked = toggle.checked; });
          recount();
        });
        checks.forEach(function(c){ c.addEventListener('change', recount); });
        recount();
      })();
    </script>
  </div>`;
}

/* ─── Bulk-delete confirmation page ─── */

export function renderBulkDeleteConfirm(opts: {
  clients: readonly ClientRow[];
  errors: string[];
  /** Where to navigate after success/cancel — `/app/generated-sites` or `/app/clients`. */
  returnTo: string;
}): string {
  const { clients, errors, returnTo } = opts;
  const errBox =
    errors.length > 0 ? `<div class="error-box">${errors.map(esc).join("\n")}</div>` : "";
  const liveCount = clients.filter((c) => !c.deleted_at).length;
  const alreadyDeletedCount = clients.length - liveCount;

  if (liveCount === 0) {
    return `<div class="client-detail" style="max-width:720px">
      <div class="crumbs"><a href="${esc(returnTo)}">← Back</a></div>
      <h1>Nothing to delete</h1>
      <div class="empty">All ${clients.length} selected client${clients.length === 1 ? " is" : "s are"} already soft-deleted.</div>
    </div>`;
  }

  const rows = clients
    .map(
      (c) => `<tr${c.deleted_at ? ' style="opacity:.55"' : ""}>
        <td class="mono">${esc(c.client_id)}${c.deleted_at ? ' <span style="color:var(--amber);font-size:.75rem">(already deleted, skipped)</span>' : ""}</td>
        <td class="mono" style="font-size:.85rem">${esc(c.proxy_domain)}</td>
        <td class="mono" style="font-size:.78rem;color:var(--fg-muted)">${esc(c.status)}</td>
      </tr>`,
    )
    .join("");

  const hiddenFields = clients
    .filter((c) => !c.deleted_at)
    .map((c) => `<input type="hidden" name="client_id" value="${esc(c.client_id)}">`)
    .join("");

  return `<div class="client-detail" style="max-width:720px">
    <div class="crumbs"><a href="${esc(returnTo)}">← Back</a></div>
    <h1 style="color:var(--red)">Bulk delete ${liveCount} site${liveCount === 1 ? "" : "s"}</h1>
    ${errBox}
    <div style="background:var(--red-bg);border:1px solid color-mix(in srgb,var(--red) 30%,transparent);border-radius:var(--radius);padding:1rem 1.25rem;margin-bottom:1.25rem">
      <strong>This will soft-delete ${liveCount} site${liveCount === 1 ? "" : "s"}.</strong>
      ${alreadyDeletedCount > 0 ? `<div style="color:var(--fg-muted);font-size:.85rem;margin-top:.3rem">${alreadyDeletedCount} already-deleted site${alreadyDeletedCount === 1 ? "" : "s"} in your selection will be skipped.</div>` : ""}
      <ul style="margin:.5rem 0 0;padding-left:1.2rem;line-height:1.7">
        <li>Each site flips to <code>paused</code> and starts returning <code>410 Gone</code>.</li>
        <li>Hidden from list views until you toggle "Show deleted".</li>
        <li>Restore one-by-one from each client's detail page within 30 days.</li>
      </ul>
    </div>

    <table class="data" style="margin-bottom:1.25rem">
      <thead><tr><th>Client</th><th>Proxy domain</th><th>Current status</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>

    <form method="POST" action="/app/generated-sites/bulk-delete">
      ${hiddenFields}
      <input type="hidden" name="return_to" value="${esc(returnTo)}">
      <div class="form-section">
        <label for="confirm_word">Type <code style="font-family:var(--mono);font-weight:700">DELETE</code> to confirm:</label>
        <input id="confirm_word" name="confirm_word" type="text" required autocomplete="off" autofocus placeholder="DELETE" style="font-family:var(--mono);font-size:1rem;text-transform:uppercase">
      </div>
      <div class="form-actions">
        <button class="btn" type="submit" style="background:var(--red);border-color:var(--red);color:#fff">Soft-delete ${liveCount} site${liveCount === 1 ? "" : "s"}</button>
        <a class="btn" href="${esc(returnTo)}">Cancel</a>
      </div>
    </form>
  </div>`;
}

/* ─── Bulk-delete POST handler ─── */

export interface BulkDeleteResult {
  deleted_ids: string[];
  skipped_already_deleted: string[];
  errors: Array<{ client_id: string; message: string }>;
}

export async function handleBulkDeletePost(
  request: Request,
  env: AppEnv,
  url: URL,
  user: User,
): Promise<Response> {
  const csrf = checkCsrf(request, url);
  if (csrf) return csrf;
  const form = await request.formData();
  const ids = form.getAll("client_id").filter((v): v is string => typeof v === "string");
  const confirm = String(form.get("confirm_word") ?? "")
    .trim()
    .toUpperCase();
  const returnTo = String(form.get("return_to") ?? "/app/generated-sites");

  if (ids.length === 0) {
    return flashRedirect(returnTo, { text: "No sites selected.", kind: "err" });
  }
  if (confirm !== "DELETE") {
    // Re-render the confirm page with the original list so the operator
    // can fix the typo without losing their selection.
    const clients = await loadClientsByIds(env, user, ids);
    const html = renderBulkDeleteConfirm({
      clients,
      errors: [`Confirmation word didn't match: expected "DELETE", got "${confirm || "(empty)"}".`],
      returnTo,
    });
    // Pass the confirm-page HTML back via a synthetic response so the
    // route handler can wrap it in the standard appLayout. Simpler:
    // just flashRedirect with the error and let the operator re-tick.
    void html;
    return flashRedirect(returnTo, {
      text: `Confirmation didn't match — expected "DELETE", got "${confirm || "(empty)"}".`,
      kind: "err",
    });
  }

  const result: BulkDeleteResult = {
    deleted_ids: [],
    skipped_already_deleted: [],
    errors: [],
  };

  // Sequential to keep audit log + KV updates atomic per-client. With
  // hundreds of clients this is a few seconds; acceptable for an
  // operator-triggered admin action.
  for (const id of ids) {
    const client = await loadVisibleClient(env, user, id);
    if (!client) {
      result.errors.push({ client_id: id, message: "not found or not visible" });
      continue;
    }
    if (client.deleted_at) {
      result.skipped_already_deleted.push(id);
      continue;
    }
    let parsedCfg: Record<string, unknown>;
    try {
      parsedCfg = JSON.parse(client.config_json);
    } catch (e) {
      result.errors.push({ client_id: id, message: `bad config_json: ${(e as Error).message}` });
      continue;
    }
    parsedCfg.status = "paused";
    const newJson = JSON.stringify(parsedCfg);

    try {
      await env.CONFIG_DB.prepare(
        `UPDATE clients
           SET status = 'paused',
               deleted_at = CURRENT_TIMESTAMP,
               config_json = ?,
               updated_at = CURRENT_TIMESTAMP
         WHERE client_id = ?`,
      )
        .bind(newJson, id)
        .run();
      await invalidateKv(env, id, client.proxy_domain);
      const actor = actorOf(user, request);
      await writeAudit(env, {
        client_id: id,
        actor_email: actor.user.email,
        actor_ip: actor.ip,
        event_type: "soft_delete",
        before_hash: fnvHash(client.config_json),
        after_hash: fnvHash(newJson),
        previous_status: client.status,
        new_status: "paused",
        notes: `Bulk delete (batch of ${ids.length}).`,
      });
      result.deleted_ids.push(id);
    } catch (e) {
      result.errors.push({ client_id: id, message: (e as Error).message });
    }
  }

  const parts: string[] = [];
  if (result.deleted_ids.length > 0) {
    parts.push(`${result.deleted_ids.length} soft-deleted`);
  }
  if (result.skipped_already_deleted.length > 0) {
    parts.push(`${result.skipped_already_deleted.length} already deleted (skipped)`);
  }
  if (result.errors.length > 0) {
    parts.push(`${result.errors.length} error${result.errors.length === 1 ? "" : "s"}`);
  }
  const kind: FlashMessage["kind"] = result.errors.length > 0 ? "warn" : "ok";
  return flashRedirect(returnTo, {
    text: `Bulk delete: ${parts.join(", ")}.`,
    kind,
  });
}

/**
 * Load a batch of clients by ids, respecting per-user visibility. Used
 * by the bulk-delete confirmation page to show the operator exactly
 * what they're about to delete.
 */
export async function loadClientsByIds(
  env: AppEnv,
  user: User,
  ids: readonly string[],
): Promise<ClientRow[]> {
  if (ids.length === 0) return [];
  // D1 doesn't expose IN with bound array, so build placeholders.
  const placeholders = ids.map(() => "?").join(",");
  const sql = canSeeAllClients(user)
    ? `SELECT * FROM clients WHERE client_id IN (${placeholders}) ORDER BY client_id`
    : `SELECT * FROM clients WHERE client_id IN (${placeholders}) AND owner_id = ? ORDER BY client_id`;
  const stmt = env.CONFIG_DB.prepare(sql);
  const bound = canSeeAllClients(user) ? stmt.bind(...ids) : stmt.bind(...ids, user.id);
  const r = await bound.all<ClientRow>();
  return r.results ?? [];
}
